app:
    social:
        naver:
            clientid: ${SOCIAL_NAVER_CLIENT_ID}
            clientsecret: ${SOCIAL_NAVER_CLIENT_SECRET}
            domain: ${SOCIAL_NAVER_DOMAIN}
            popupurl: https://nid.naver.com/oauth2.0/authorize
            profileurl: https://openapi.naver.com/v1/nid/me
            redirecturl: ${SOCIAL_NAVER_REDIRECT_URL}
            tokenurl: https://nid.naver.com/oauth2.0/token
auth-code-expiration-seconds: 180
auth-email-title: 'gameblog signup request'
jwt:
    key: ${JWT_SECRET_KEY}
    access-expire-time: ${ACCESS_EXPIRE_TIME}
    refresh-expire-time: ${REFRESH_EXPIRE_TIME}


spring:
    application:
        name: GameBlog
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${MYSQL_PASSWORD}
        url: jdbc:mysql://127.0.0.1:3306/blog
        username: ${MYSQL_USER}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    mail:
        host: smtp.gmail.com
        password: ${SMTP_APP_PASSWORD}
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    starttls:
                        enable: true
                        required: true
                    timeout: 5000
                    writetimeout: 5000
        username: ${SMTP_EMAIL}
    # OAuth 로그인
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${SOCIAL_GOOGLE_CLIENT_ID}
                        client-secret: ${SOCIAL_GOOGLE_CLIENT_SECRET}
                        scope:
                            - email
                            - profile
                    naver:
                        client-id: ${SOCIAL_NAVER_CLIENT_ID}
                        client-secret: ${SOCIAL_NAVER_CLIENT_SECRET}
                        scope:
                            - name
                            - email
                        client-name: Naver
                        authorization-grant-type: authorization_code
                        redirect-uri: http://localhost:8080/login/oauth2/code/naver
                provider:
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response